### ISSUE TITLE
implementing versioning

### ISSUE THREAD

**Issue by zayd62** [zayd62/mkdocs-versioning#4]
**Note:**
- whenever software is ready for release, it should have a git annotated tag
- the tag should respect [semver](https://semver.org/) but that's not necessary

There are two ways of implementing versioning 

# Method 1: seperate nav page

This is the original idea where directory structure looks like this
```
.
├── 1.0.0
│   ├── index.html
│   └── ...
├── 1.1.1
│   ├── index.html
│   └── ...
├── 2.0.0
│   ├── index.html
│   └── ...
├── index.html
└── ...
```

where the numbers (1.0.0, 1.1.0, ...) are folders containing the **built** documentation for that specific version. ```index.html``` in the root directory is a web page with links to index.html for each built version

each built version has a nav item that points to ```../``` (which points to ```index.html``` in the **root directory**). This means that whenever a new version is built, the newly built version  has a nav item that points to ```../``` and the `index.html` will have a new pointer to the newly built version

# Method 2

each built version has a nav item pointing to other versions built.

eg **1.0.0** has a nav item pointing nowhere. when **1.1.0** is built, **1.0.0** has a nav item pointing to **1.1.0** and **1.1.0** has a nav item pointing to 1.0.0 etc. when ever a new version is released, ensure that **all built versions** have pointers to all the other **built versions**

problem with this approach is that when ever a new version is released, all version prior need to have the new version added to the nav and rebuilt. say you have 10 versions and an 11th is released, all 11 will have to be rebuilt. Method 1 avoids this by having a centrally updating versions page so only 2 versions need to be built (the 11th version and the central version page). method 1 means that you have to go to an entirely different page

The beta has method 1 but could change for the 1.0.0 release

**Comment by pawamoy** [comment]
Here is a different approach:

Each version uses a small javascript snippet to dynamically add the navigations items (the other versions) to the sidebar, by loading them from a JSON file one directory above.

Benefits:

- No root page with the nav items
- ...meaning less clicks to get to the desired version
- Possible to change version **while staying on the same item** (I would be particularly interested in this feature)
- Only one file to rebuild for each new docs version (the root `versions.json`)
- Could be easily made compatible with, or add support for language versions
- Possible to have `latest` and `stable` pointers with simple, auto-updated symlinks (though I guess this one is already doable with the current approach)

Downsides:

- Every single documentation page has to run this javascript snippet to dynamically build the nav items for the versions. However it's a kinda light snippet I believe. And mkdocs themes are already using javascript I think?

```
.
├── 1.0.0/
│   ├── index.html
│   └── ...
├── 1.1.1/
│   ├── index.html
│   └── ...
├── 2.0.0-rc1/
│   ├── index.html
│   └── ...
├── index.html -> stable/index.html
├── latest -> 2.0.0-rc1/
├── stable -> 1.1.1/
└── versions.json
```

Upon building a new docs version, simply rewrite the `versions.json` file, and update the `latest` and `stable` symlinks.

Rewriting `versions.json` is done by listing the current versions (the directories), and adding the currently built version to this list, writing it as JSON.

Then the javascript snippet in each version would be something like:

```javascript
$.getJSON("/project_name/versions.json", function(data) {
  var nav = $(...)  # get the nav
  var versions = nav.append("some html markup")
  for each (version in data) {
    var url = "/project_name/" + version
    versions.append(version )
  }
})
```

However I'm not sure how we would know what markup to use since it depends on the theme used... Maybe each theme could provide this snippet? Or we would have these different snippets in separate repos/projects? Maybe we would have the users add it themselves?


We can also get inspiration from the Python docs. They seem to have the versions in a javascript file used to switch between them (each version has its own copy, I'm guessing they are all updated for each new version, which is rare enough). Instead of pre-building the links, they use an event to redirect to the first existing page from a list:

```javascript
 var all_versions = {
  '3.9': 'dev (3.9)',
  '3.8': '3.8',
  '3.7': '3.7',
  '3.6': '3.6',
  '3.5': '3.5',
  '2.7': '2.7',
}

// build the <select> item...

function on_version_switch() {
  var selected_version = $(this).children('option:selected').attr('value') + '/';
  var url = window.location.href;
  var current_language = language_segment_from_url(url);
  var current_version = version_segment_in_url(url);
  var new_url = url.replace('.org/' + current_language + current_version,
    '.org/' + current_language + selected_version);
  if (new_url != url) {
    navigate_to_first_existing([
      new_url,
      url.replace('.org/' + current_language + current_version,
        '.org/' + selected_version),
      'https://docs.python.org/' + current_language + selected_version,
      'https://docs.python.org/' + selected_version,
      'https://docs.python.org/'
    ]);
  }
}

function navigate_to_first_existing(urls) {
  // Navigate to the first existing URL in urls.
  var url = urls.shift();
  if (urls.length == 0) {
    window.location.href = url;
    return;
  }
  $.ajax({
    url: url,
    success: function() {
      window.location.href = url;
    },
    error: function() {
      navigate_to_first_existing(urls);
    }
  });
}
```

**Comment by zayd62** [comment]
The problem with your approach is that each theme does navigation differently. take a look at the html source code for different themes for example (right-click --> inspect element in chrome for example), [the default theme](https://www.mkdocs.org/) and [mkdocs-material](https://squidfunk.github.io/mkdocs-material/)

Also, another issue is that mkdocs is a **static site generator**. inserting content after the docs are built isn't what mkdocs is designed to do. sure there are dynamic elements such as dropdowns but they work under the assumption that all the content is built and no new content is added

The main issues I have are
- Design the versioning in such a way that it is **theme agnostic**. i.e. it works with every theme
  - A seperate version page that is built using the same mechanism as mkdocs uses
- **minimal** changes to documentation workflow. 
  - simply change version number in mkdocs.yml
- avoid changing historical version numbers
  - i dont think you should be changing previous version of the docs. 

Maybe we could have some javascript inserting some `<ul></ul>` and `<li></li>` elements but that works under the assumption that the theme does not do anything with the elements like adding `id` or `class` attributes

**Comment by zayd62** [comment]
Decided not to change versioning mechanism due to lack of activity and deciding to focus on getting plugin out of beta, close issues and get a 1.0.0 release. If you would like to discuss this further, then feel free to open a new issue
