### ISSUE TITLE
Style not applied when coming from extra stylesheet

### ISSUE THREAD

**Issue by ppanero** [zayd62/mkdocs-versioning#48]
When the CSS for the page comes from a stylesheet, e.g. with the following in the `mkdocs.yaml`:

```yaml
extra_css:
  - stylesheets/extra.css
```

Then the version page does not load the CSS. Example:

**Properly styles version 0.7.2**

![Screenshot 2020-03-30 at 09 30 11](https://user-images.githubusercontent.com/6756943/77886829-d641f200-7269-11ea-9d48-52c4beb9a580.png)

**Version page without CSS**:

![Screenshot 2020-03-30 at 09 29 56](https://user-images.githubusercontent.com/6756943/77886878-ebb71c00-7269-11ea-8ff2-47f45a287cae.png)

**Why does this happen?**

When building the extra `stylesheets` folder is not present in the main directory:

```console
% tree site -L 1
site
├── 0.7.1
├── 0.7.2
├── 404.html
├── assets
├── index.html
├── search
├── sitemap.xml
└── sitemap.xml.gz
```

``` console
% tree site/0.7.2 -L 1
site/0.7.2
├── 404.html
├── assets
├── deployment
├── develop
├── extensions
├── images
├── index.html
├── install
├── preview
├── sitemap.xml
├── sitemap.xml.gz
└── stylesheets
```

Note that this happens with the `images` folder too. I understand parsing the whole `mkdocs` file in search of folder to add to the build is a tedious/impossible to do properly with the resources at hand task. Maybe setting some conventions for naming would be enough.

It is a platform independent bug.

**Comment by zayd62** [comment]
do you have a repo I can look at since you also have #49 so I can figure out what is happening and sort out both issues

**Comment by ppanero** [comment]
Hi @zayd62 the repo is https://github.com/inveniosoftware/docs-invenio-rdm

Ill check this fixes asap. Thanks!

**Comment by zayd62** [comment]
# What's going wrong

so I think I have figured out the problem. in your `mkdocs.yml`, there are a whole bunch of relative paths. not just in the `extra_css` but also in the theme configuration (`custom_dir`, `logo`, `favicon`). everything looks incorrect because of the relative links. 

# Why

the reason this is messed up is because the `docs_dir` option in `mkdocs.yml` is changed when building the version selector which messes up the relative links. The reason `docs_dir` option in `mkdocs.yml`  is changed is because mkdocs automatically builds all the md files in `docs_dir` even if it is not mentioned in the nav in `mkdocs.yml`.  in order to be **theme and plugin agnostic**, I cant be iterating through the config, finding relative paths, converting into the correct absolute paths. A solution is to simply leave the `docs_dir` as default which then raises another issue

a `version_page.md` file is needed (thats the page that says "welcome to the version selection page, use the navigation menu to go to different doc versions"). if i leave `docs_dir` as default, the version selection page will by default display `index.md` which then raise the issue 

> how do you differentiate between the version selection page and the actual docs if they both share the same page content. The only difference will be the navigation items

# Potential Solution

one solution is to 
1. rename the original index.md (or README.md which according to mkdocs is also a suitable replacement. which is written by the author ) to index.md.bak, 
2. rename the `version_page.md` as `index.md`, let the docs built so that the custom page can be used, 
3. delete `version_page.md` (which at this stage is called `index.md`) and rename `index.md.bak` back to `index.md`

now the problem with this is that when i run build the second time, what happens is that it builds all the md files but in the nav, it does not display links to the other items.

for example,`http://0.0.0.0:8000/` will bring you to a standard version selection page but typing **explicitly** `http://0.0.0.0:8000/deployment` for example will load up a built page (specifically `/docs/deployment/index.md`) this page (amongst others) should **NOT** be built. 

> note that the only way to access these *"hidden"* pages is to know what urls to type. It does not show up as a nav item as it is not specified in the version page nav

So a couple of solutions i came up with:

1. move all the user built docs into a temporary folder using [tempfile](https://docs.python.org/3.7/library/tempfile.html) leaving the `/docs/` directory empty, insert the `version_page.md` file renamed to `index.md`. once the version selection page is built, copy back the user docs from the temporary folder into `/docs/`. However, it does use the [os specific temporary directory](https://docs.python.org/3.7/library/tempfile.html#tempfile.gettempdir) and if the program fails between moving the docs to/from the temporary directory or even during the copy, the docs can get corrupted/lost

2. compress user written docs into a zip file. compressing the user docs into a zip file then removing the user built docs. build the version page and decompress the user docs.

either solution I think of involves interacting with the md files which can get corrupted which I am not a fan off

# conclusion

fixing the styling cause another issue which can be fixed although im not a fan of the solutions I came up with.

**Comment by ppanero** [comment]
@zayd62 Thanks a lot for the work, I will check all this during the weekend :) Thanks!

**Comment by zayd62** [comment]
https://github.com/zayd62/mkdocs-versioning/tree/build-version-errors is what I've done so far.

**Comment by zayd62** [comment]
hey @ppanero, fixed this issue, updated documentation and made it available on pypi. latest version is 0.3.0. recommend reading through the documentation https://zayd62.github.io/mkdocs-versioning/ as there are significant changes

**Comment by ppanero** [comment]
Thanks! @zayd62
