### ISSUE TITLE
mkdocs-versioning sync creates a .git directory

### ISSUE THREAD

**Issue by mirestrepo** [zayd62/mkdocs-versioning#54]
**Describe the bug**
When running `mkdocs-versioning sync` a `.git` directory is created under site.
If you later try to do `mkdocs-versioning deploy`, it will fail with 

```
 Failed to deploy to GitHub with error: 
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
```

**To Reproduce**

```
mkdocs-versioning sync
mkdocs-versioning deploy
```

**Expected behavior**
Manually removing the `site/.git` directory solves the issue. However this is probably not the desired flow, or it is is, then it should be documented

**Desktop (please complete the following information):**
 - OS: macOS Mojave

Thank you for this awesome package!

**Comment by zayd62** [comment]
Hey there, thanks for the bug report. I think i know where in the code this error occurs and where to apply the fix; just a matter of getting around to it. However, due to other commitments, I will (most likely) **not** be able to address the issue straight away. I'll try and tackle this over the weekend. 

Also, just to cover all bases, could you run pip freeze and paste the output. This is just to make sure there is no issues with dependencies or other packages that you have installed. The ```sync``` command depends on the actual``` mkdocs``` package so this is just to make sure that there hasnt been any changes made with ```mkdocs``` that broke the command

**Comment by zayd62** [comment]
hey @mirestrepo i think i have solved the issue for you. before i push the changes to pypi, could you test it out for me:

1. uninstall the plugin through pip: ```pip uninstall mkdocs-versioning```
2. clone the repositiory: ```git clone mkdocs-versioning```
3. switch to the fixes branch: ```git checkout fixes```
4. install the plugin locally: pip install -e <path to root of the repo>
5. try running a sync and deploy and see if the bug occurs again

if its woking on your end too, i will push to master and then pypi

**Comment by zayd62** [comment]
changes fixed and merged into master, available of pypi
