### ISSUE TITLE
Make home page redirect to latest version

### ISSUE THREAD

**Issue by Toilal** [zayd62/mkdocs-versioning#58]
**Is your feature request related to a problem? Please describe.**
Most user wants to see latest version page by default, but home page points to version selector.

**Describe the solution you'd like**
There should be an option to make default home page redirect to latest version.

**Describe alternatives you've considered**
mkdocs-redirects, but I can't really achieve what I want.

**Additional context**

**Comment by zayd62** [comment]
I've toyed with this idea for a while and with the plugins current design, it could be possible but it will be a lot of work. If you take a look at the documentation on how the plugin works under the hood, https://zayd62.github.io/mkdocs-versioning/0.3.0/reference/ you would know that the home page (https://zayd62.github.io/mkdocs-versioning/) would lead to the version selection page. and that adding a new version is done by

1. building new version of the docs into a new folder in the `site` directory
2. update the version selection page

The important point is that **the version selection page depends on the `site` directory structure to build the version selection page**. if the homepage was the latest version, there would essentially be a _missing version_ from the version selection page. 

The plugin is built around these core requirements https://zayd62.github.io/mkdocs-versioning/0.3.0/#design and any new enhancements need to satisfy these core requirements. I can't think of an easy way to keep track of the versions built while maintaining the core requirements without somehow keeping track of state which I do not want to do. 


a solution off the top of my head: 
1. build everything into its own folder in the site directory including the version selection pages
2. have `index.html` auto-redirect you to the latest version (with some javascript maybe???) (how to determine latest version???)
3. appropriately set the redirects in the links to the version selection page. (currently it is just a relative link)

perhaps a directory structure like this
```
.
├── 0.1.0
├── 0.2.0
├── 0.3.0
├── index.html
└── version-selector
```

It definitely requires a lot more thinking and whether or not this behaviour should be default. if this is optional behaviour (which it should be) then there will definitely be a code refactor in order to facilitate this feature and a ground up code refactor is not something that I'd really want to do (although I should, not too happy with the code anyways)

perhaps if you could let me know why you really want this feature and see if https://zayd62.github.io/mkdocs-versioning/0.3.0/reference/config_options/#option-version_selection_page can satisfy your needs
